### ISSUE TITLE
1,07GB file bug ?

### ISSUE THREAD

**Issue by 12georgiadis** [ucnv/aviglitch#2]
Hi, when I use aviglitch and command $ datamosh, it always cut my avi file to 1,07GB. Whatever if it is 3GB fil source, 4GB or more... So I don't think it is related to the 32Bits 4,7GB avi limit. Config is Mac Os Yosemite and files are between 4K and 6K, x264 100mbps (less than 1' and 2 or 3 cuts max). Regards, IJC

**Comment by 12georgiadis** [comment]
same in osx sierra

**Comment by jacques-perconte** [comment]
Slice your file with ffmpeg

---

En ligne Impressions, 2012, 48' https://vimeo.com/38519895

Jacques Perconte
+33 660 615 408

http://www.jacquesperconte.com

→ http://timeline.technart.fr / news
→ https://twitter.com/jacquesperconte / voix

**Comment by 12georgiadis** [comment]
Thanks for the tip, I forgot that there was this function in ffmpeg

**Comment by jacques-perconte** [comment]
ffmpeg -i "input.avi" -acodec copy -f segment -segment_time 120 -vcodec
copy -reset_timestamps 1 -map 0 output%2d.avi

;)

j.

☀︎
En ligne Impressions, 2012, 48' https://vimeo.com/38519895

Jacques Perconte
+33 660 615 408

http://www.jacquesperconte.com

→ http://timeline.technart.fr / news
→ https://twitter.com/jacquesperconte / voix

**Comment by 12georgiadis** [comment]
Great! I'll give a try with these main options command. Good news is that I can even improve the bitrate to be closer to the raw footage. Many thx, I

**Comment by jacques-perconte** [comment]
There is always a solution +
j.


http://www.jacquesperconte.com

→ http://timeline.technart.fr / news
→ https://twitter.com/jacquesperconte / voix

**Comment by ucnv** [comment]
Hi @12georgiadis  
Over 4 years passed since you reported this issue...!
I have released new version of the library which should solve this issue.

The problem was that this library didn't support the advanced AVI format which is generally called AVI2.0.
In the latest version it was totally refined to handle AVI 2.0 files. 
And now we finally can process the files larger than 1GB.

Please check the new version of AviGlitch (if you're still in there)...!

Also thank @jacques-perconte for the conversation.
